### ISSUE TITLE
Same instance?

### ISSUE THREAD

**Issue by schloerke** [Bart6114/jug.parallel#1]
Thank you for the jug package! Very user friendly and very quick to pick up coming from node.js express!

Question on the parallel extension: Does each jug instance have the same memory? For example: if I have a website hit counter, will I have 8 different counters or one single counter used by all 8 jug instances.

Thank you!
Barret

**Comment by bart6114** [comment]
Hi @schloerke,
Each jug instance is created identical to the original jug instance. However, they are separate processes and, while sharing the same initial state, they do not share the same memory. That also means that, for now, there is no user and/or session stickyness.

Specifically for you example, at this point there is no fix in `jug.parallel`. I'm also not really sure if it should be fixed at `jug` level as generally this challenge is overcome by using the same data storage backend which each instance can connect to. 

If this does not answer you question, feel free to reopen.

**Comment by schloerke** [comment]
That is what I guessed. And using a small backend for consistent state is an easy fix. 

Thank you!
